# Use Python 3.8 base image
FROM python:3.8-slim

# Set the working directory
WORKDIR /app

# Copy the service code
COPY . /app/

# Install curl
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

# Install dependencies
RUN pip install Flask

# Expose port
EXPOSE 5001

# Command to run the service
CMD ["python", "service_b.py"]
