# Use Python 3.8 base image
FROM python:3.8-slim

# Set the working directory
WORKDIR /app

# Copy the service code
COPY . /app/

# Install dependencies
RUN pip install Flask

# Expose port
EXPOSE 5000

# Command to run the service
CMD ["python", "service_a.py"]
