apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: b-service
spec:
  host: b-mtls-service.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
      credentialName: istio-ingressgateway-certificate