apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: services-gateway
  namespace: default
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: mkcert-credentials
    hosts:
    - python.example.net
