apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-virtual-service
  namespace: default
spec:
  hosts:
  - c-mtls-service.default.svc.cluster.local
  gateways:
  - services-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: c-mtls-service.default.svc.cluster.local
        port:
          number: 5002