apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-net-domain-cert
  namespace: default
spec:
  secretName: example-net-ingressgateway-certificate
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  commonName: example.net
  dnsNames:
  - "*.example.net"
  # Optional: Set the duration of the certificate validity
  duration: 2160h
  renewBefore: 360h
